baseurl = "https://ai-gemini.github.io"
title = "ai gemini"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en"
resourceDir = "../resources"
DefaultContentLanguage = "en"
Paginate     = false

PygmentsCodeFences = true
PygmentsStyle      = "monokai"


buildFuture = true

[author]
     name = "wahyu6070"
     
[sitemap]
  changefreq = "always"
  priority = 0.8
  filename = "sitemap.xml"
[permalinks]
  link     = "/:year:month:day/:slug"
  
[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "LiteGapps is a custom Google Apps on the Android operating system, an open source project that focuses on small, efficient, and comprehensive."
  recent_posts_number = 3
  